run:
  timeout: 5m
  go: "1.21.6"

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/yan-aint-nickname/tanuki
  misspell:
    locale: US
  lll:
    line-length: 120


linters:
  disable-all: true
  enable:
    - dogsled
    - dupl
    - errcheck
    - fatcontext
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
